image: node:lts-alpine

lint on commit:
  stage: build
  script:
   - yarn install
   - yarn run lint
  only:
   - merge_requests

pages:
  stage: deploy
  script:
   - yarn install
   - yarn run build
   - rm -rf public
   - mkdir -p public
   - cp -r dist/* public
  artifacts:
    paths:
    - public
  only:
   - master